### ISSUE TITLE
Crash when ending poll after user is removed

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/Formbar.js#221]
Related to #220 

### Error on Server
```
C:\Users\Samisu\Documents\GitHub\Formbar.js\app.js:1240
                data.prompt = cD[socket.request.session.class].poll.prompt
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'prompt')
    at Socket.<anonymous> (C:\Users\Samisu\Documents\GitHub\Formbar.js\app.js:1240:55)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\socket.io\dist\socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### How to Reproduce

- Teacher starts a class
- Student joins class
- Teacher starts poll
- Teacher 'deletes' Student from class
- Teacher ends poll

### May be related
```
C:\Users\Samisu\Documents\GitHub\Formbar.js\app.js:1196
                cD[socket.request.session.class].poll.blind = blind
                                                            ^

TypeError: Cannot set properties of undefined (setting 'blind')
    at Socket.<anonymous> (C:\Users\Samisu\Documents\GitHub\Formbar.js\app.js:1196:47)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\socket.io\dist\socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by csmith1188** [comment]
The issue seems to be it's checking cD for a key that is not longer in cD, because the user was removed already.

Does the Delete User button log the user out, or does it just remove their data from the cD?

**Comment by csmith1188** [comment]
Before ending the poll, but after deleting the user, refresh the page. You will get this error on the Teacher client.
```
TypeError: Cannot read properties of undefined (reading 'classPermissions')
    at permCheck (C:\Users\Samisu\Documents\GitHub\Formbar.js\app.js:216:37)
    at Layer.handle [as handle_request] (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\route.js:144:13)
    at isAuthenticated (C:\Users\Samisu\Documents\GitHub\Formbar.js\app.js:177:4)
    at Layer.handle [as handle_request] (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Samisu\Documents\GitHub\Formbar.js\node_modules\express\lib\router\index.js:346:12)
```
