### ISSUE TITLE
More Permissions Crashes

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/Formbar.js#250]
```
/home/pi/formjs/app.js:559
                cD[key].students[req.session.username].classPermissions = MANAGER_PERMISSIONS
                                                                        ^

TypeError: Cannot set properties of undefined (setting 'classPermissions')
    at makeClass (/home/pi/formjs/app.js:559:59)
    at Statement.<anonymous> (/home/pi/formjs/app.js:593:4)
    at Statement.replacement (/home/pi/formjs/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.replacement (/home/pi/formjs/node_modules/sqlite3/lib/trace.js:25:27)
```

Still trying to determine cause.

**Comment by csmith1188** [comment]
Testing on most recent Dev branch

**Comment by mason26611** [comment]
Closing this as this error occurred with code that has significantly changed, and this error doesn't seem to be occurring anymore.
